# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
---
version: 2
updates:
#  - package-ecosystem: "bun"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#    open-pull-requests-limit: 10
#    groups:
#      payload-monorepo:
#        patterns:
#          - "payload"
#          - "@payloadcms/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
